apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "nsvalidation-webhook.fullname" . }}-sa"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nsvalidation-webhook.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-200"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ include "nsvalidation-webhook.fullname" . }}-sa-binding"
  labels: 
    {{- include "nsvalidation-webhook.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-150"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-failed
subjects:
  - kind: ServiceAccount
    name: "{{ include "nsvalidation-webhook.fullname" . }}-sa"
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

