

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "nsvalidation-webhook.fullname" . }}
webhooks:
  - name: "{{ include "nsvalidation-webhook.fullname" . }}.{{ .Values.namespace }}.svc.cluster.local"
    admissionReviewVersions: ["v1", "v1beta1"]
    failurePolicy: Fail
    timeoutSeconds: 2
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["namespaces"]
        scope: "Cluster"
    clientConfig:
      service:
        namespace: "webhooks"
        name: "nsvalidating"
        path: "/validate"
      {{ $secret := (lookup "v1" "Secret" .Release.Namespace "cabundle").data }}
      caBundle: {{ index $secret "cabundle" | quote }}
      # caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHekNDQWdPZ0F3SUJBZ0lVWWJuR25kbnVCNVNKcURMOWNZMnV5QnhMV3JZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0hURWJNQmtHQTFVRUF3d1NZV1J0YVhOemFXOXVZVjlqWlhKMFgyTmhNQjRYRFRJME1EY3pNVEUyTlRBeQpPVm9YRFRNME1EY3lPVEUyTlRBeU9Wb3dIVEViTUJrR0ExVUVBd3dTWVdSdGFYTnphVzl1WVY5alpYSjBYMk5oCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBeVhZMmVDenZ5UVQ3STRqVHpJbFMKVWpVOEd5cTcyaGpRSFNDbjhEYWtTbVBuQlQxZCt4bmdmQWVVcFV0UE95MStxM25vTE42QUZIZHo4T0NNdFd2aAo0VUpxa2E4dFU1TkVucEtkQnFuVmhPTVhsUVp2YkhSR25YaDlBbkprTHFKaTRRNEtHQWl5RFZsc0haUSt5WGhRCmNuMEVjSzhWNkhVSXV0VVhWL2MxNUtvNXRMWm9SK1ZDUWN3cmJVZzFIU0NKTFluK3VQMkRLSGRCWGYyMW1IcjAKNi9UajZCV0EvN0lCTk5jODd5VThXQlJaRkphV1JrMFFZUnVSWDhPVFJubmZWSjRTVlJldEVNdmJJU2E2eG82aApQWmY2WWFpcHF1K1JmelNLbXZkSytqb1B2RnhFK044dTgzNXRMUWlZd0tISGZveXFCZkVWK0FVVUJDSHRTTm82CjF3SURBUUFCbzFNd1VUQWRCZ05WSFE0RUZnUVVSL1p5UktDUEpubXZzWFFJM3F4SXZuSnhGTmd3SHdZRFZSMGoKQkJnd0ZvQVVSL1p5UktDUEpubXZzWFFJM3F4SXZuSnhGTmd3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcQpoa2lHOXcwQkFRc0ZBQU9DQVFFQVg5YW9QMXhrSnFjOEkrZFlOalRVQ3FhYzlDSm9rRUp5ZEladm1PVDlGaElaCkdOV2xZK3U2eDd0TzJiWFpLenZWUU0vNWh4RTNES0dLM0JqU2p6aFhJVnpTTVB6dHJwVXdJRDJMWlRqTGVJb1IKRnRHRW1qdVRZTkI5eER4R3poNUNPaVNJS1M5eFB3U2cvNU5XWGZ6MFNOcE9oOXdlUE9UWWZINTdudXg5b1hMTgp5RjhQWGtFajgvYnBkNEVaQUNmSlhUYjVMN1MySDFxNnBFcjlCVFUzNU81OXgwZjNWNlpiL0QzU3pQdlhOWEs3CkpRZGM0MmNYckNldGNXMUpJcHpsL0o1YjVnb1g4ZTdWSXUvMHJLMmpIZm10UnVBdXVIOFRaZUM2SHE2bkZnRXoKVytxaUd0dDhmbXIzV3ZkOTdMZEFDUDhNMHNQemRuMFRxMUJudCtJZUJ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5